GET http://localhost:3003/api/blogs 

###
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "this blog has a user",
    "author": "SY17",
    "url":"https://www.dafk.net/what/",
    "likes": "222",
    "userId": "61b21f29adb1b30d418f2b73"
}

###
GET http://localhost:3003/api/users

###
POST http://localhost:3003/api/users
Content-Type: application/json

{
    "username": "CarlJohnson",
    "name": "YoungMaylay",
    "password": "12345"
}